<?php
/**
 * @file
 *
 */

/*
 * Implements hook_init()
 */
function developinfo_init() {

}

/**
 * Implements hook_menu()
 */
function developinfo_menu() {
  $items = array();

  $items['develop/nodejs/demo/one'] = array(
    'title' => 'Report',
    'page callback' => '_develop_nodejs_demo_one',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/develop_nodejs_demo.page.inc',
  );

  return $items;
}
