<?php
/**
 * @file
 *
 */

/**
 * Implements hook_init()
 */
function jsoninfo_init() {
  // $SourceJson = new SourceJson();
  // OtherCommonJson::saveDataToJson($SourceJson->termBrandData(), 'shoppage/category/list/brand.json');
}

/**
 * Implements hook_menu()
 */
function jsoninfo_menu() {
  $items = array();

  /** - - - - node - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  */
  // order
  $items['jsoninfo/node/recordlog/basic-values'] = array(
    'title' => 'Create JSON',
    'page callback' => '_jsoninfo_node_recordlog_basic_values',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/jsoninfo_node_output.page.inc',
  );

  /** - - - - term - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  */
  // $items['jsoninfo/term/brand'] = array(
  //   'title' => 'Create JSON',
  //   'page callback' => '_jsoninfo_term_all_brand_data',
  //   'access arguments' => array('access content'),
  //   'type' => MENU_CALLBACK,
  //   'file' => 'inc/jsoninfo_term_output.page.inc',
  // );

  /** - - - - user - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  */
  // $items['jsoninfo/user/all-user'] = array(
  //   'title' => 'User List JSON',
  //   'page callback' => '_jsoninfo_user_all_user_data',
  //   'access arguments' => array('access content'),
  //   'type' => MENU_CALLBACK,
  //   'file' => 'inc/jsoninfo_user_output.page.inc',
  // );

  return $items;
}
