<?php
/**
 * @file
 *
 */

/**
 * Implements hook_init()
 */
function libraryinfo_init() {
  drupal_add_library('libraryinfo', 'libraryinfo_font_awsome');
  drupal_add_library('libraryinfo', 'libraryinfo_angularjs');
  drupal_add_library('libraryinfo', 'libraryinfo_chart_js');

  drupal_add_library('libraryinfo', 'libraryinfo_angularjs_material');
}

/**
 * Implements hook_library().
 *
   drupal_add_library('libraryinfo', 'libraryinfo_angularjs');
 *
 */
function libraryinfo_library() {
  $libraries = array();

  /**
   * "AngularJS "
   */
  $libraries['libraryinfo_angularjs'] = array(
    'title' => 'AngularJS',
    'version' => '1.4.7',
    'website' => 'https://angularjs.org/',
    'js' => array(
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-route.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-animate.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-aria.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-sanitize.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-messages.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-resource.min.js' => array('type' => 'external'),
      'https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.14.3/ui-bootstrap.js' => array('type' => 'external'),
      'https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.14.3/ui-bootstrap-tpls.min.js' => array('type' => 'external'),
    ),
  );

  /**
   * "Angular Material"
   */
  $libraries['libraryinfo_angularjs_material'] = array(
    'title' => 'Angular Material',
    'version' => 'v0.11.2',
    'website' => 'https://github.com/angular/material#bower',
    'js' => array(
      'https://ajax.googleapis.com/ajax/libs/angular_material/0.11.2/angular-material.min.js' => array('type' => 'external'),
    ),
    'css' => array(
      'https://ajax.googleapis.com/ajax/libs/angular_material/0.11.2/angular-material.min.css' => array('type' => 'external'),
    ),
  );

  /**
   * "Chart.js" is Simple, clean and engaging charts for designers and developers
   * https://github.com/nnnick/Chart.js
   */
  $libraries['libraryinfo_chart_js'] = array(
    'title' => 'Chart JS',
    'version' => '1.0.2',
    'website' => 'http://chartjs.org/',
    'js' => array(
      'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js' => array('type' => 'external'),
      'https://cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js' => array('type' => 'external'),
      'https://cdnjs.cloudflare.com/ajax/libs/numeral.js/1.4.5/numeral.min.js' => array('type' => 'external'),
    ),
    'css' => array(
      'https://cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.css' => array('type' => 'external'),
    ),
  );

  /**
   * "Font Awesome"
   * Font Awesome is a jQuery plugin that gives you the ability to make any element on your page always stay visible.
   */
  $font_awsome_path = libraries_get_path('font-awesome-4.4.0') . '/';
  $libraries['libraryinfo_font_awsome'] = array(
    'title' => 'Font Awesome',
    'version' => 'v4.4.0 ',
    'website' => 'https://github.com/FortAwesome/Font-Awesome/',
    'css' => array(
      $font_awsome_path . 'css/font-awesome.min.css' => array(),
    ),
  );

  /** - - - - - - return - - - - - - - - - - - - - - - - - - - - - - - - - -  */

  return $libraries;
}

