<?php
/**
 * @file
 *
 */

/**
 * Implements hook_init()
 */
function libraryinfo_init() {
  drupal_add_library('libraryinfo', 'libraryinfo_angularjs');
  drupal_add_library('libraryinfo', 'libraryinfo_angularjs_material');
  drupal_add_library('libraryinfo', 'libraryinfo_chart_js');
  drupal_add_library('libraryinfo', 'libraryinfo_d3');
  drupal_add_library('libraryinfo', 'libraryinfo_font_awsome');

}

/**
 * Implements hook_library().
 *
   drupal_add_library('libraryinfo', 'libraryinfo_angularjs');
 *
 */
function libraryinfo_library() {
  $libraries = array();

  /**
   * "AngularJS "
   */
  $angularjs_path = libraries_get_path('angularjs') . '/';
  $libraries['libraryinfo_angularjs'] = array(
    'title' => 'AngularJS',
    'version' => '1.4.7',
    'website' => 'https://angularjs.org/',
    'js' => array(
      // 'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js' => array('type' => 'external'),
      $angularjs_path . 'angular.js' => array(),
      $angularjs_path . 'angular-route.min.js' => array(),
      $angularjs_path . 'angular-animate.min.js' => array(),
      $angularjs_path . 'angular-aria.min.js' => array(),
      $angularjs_path . 'angular-sanitize.min.js' => array(),
      // $angularjs_path . 'angular-resource.min.js' => array(),
    ),
    'css' => array(
      // $angularjs_path . 'custom-angular-animate.css' => array(),
    ),
  );

  /**
   * "Angular Material"
   */
  $angularjs_material_path = libraries_get_path('angular-material') . '/';
  $libraries['libraryinfo_angularjs_material'] = array(
    'title' => 'Angular Material',
    'version' => 'v0.11.2',
    'website' => 'https://github.com/angular/material#bower',
    'js' => array(
      $angularjs_material_path . 'angular-material.min.js' => array(),
    ),
    'css' => array(
      $angularjs_material_path . 'angular-material.min.css' => array(),
    ),
  );

  /**
   * "Chart.js"
   * https://github.com/nnnick/Chart.js
   * 2.0.0-alpha4
   */
  $chart_js_path = libraries_get_path('Chart.js-master') . '/';
  $libraries['libraryinfo_chart_js'] = array(
    'title' => 'Chart JS',
    'version' => '2.0.0',
    'website' => 'http://chartjs.org/',
    'js' => array(
      $chart_js_path . 'Chart.js' => array(),
    ),
  );

  /**
   *
   */
  $chart_js_path = libraries_get_path('d3') . '/';
  $libraries['libraryinfo_d3'] = array(
    'title' => 'D3',
    'version' => '3.5.16',
    'website' => 'https://d3js.org/',
    'js' => array(
      $chart_js_path . 'd3.min.js' => array(),
    ),
  );

  /**
   * load library "Font Awesome" font-awesome-4.5.0
   */
  $fontawesome_path = libraries_get_path('font-awesome-4.5.0') . '/';
  $libraries['libraryinfo_font_awsome'] = array(
    'title' => 'Font Awesome',
    'version' => '4.4.0',
    'website' => 'https://fortawesome.github.io/Font-Awesome/',
    'css' => array(
      // 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' => array('type' => 'external'),
      $fontawesome_path . 'css/font-awesome.min.css' => array(),
    ),
  );

  return $libraries;
}
