<?php
/**
 * @file
 *
 */

/**
 * Implements hook_init()
 */
function libraryinfo_init() {
  drupal_add_library('libraryinfo', 'libraryinfo_font_awsome');
  drupal_add_library('libraryinfo', 'libraryinfo_jquery_ui');
  drupal_add_library('libraryinfo', 'libraryinfo_angularjs');
  drupal_add_library('libraryinfo', 'libraryinfo_chart_js');

  drupal_add_library('libraryinfo', 'libraryinfo_angular_ui_sortable');
  drupal_add_library('libraryinfo', 'libraryinfo_angularjs_material');
  drupal_add_library('libraryinfo', 'dashpage_date_range_picker');
}

/**
 * Implements hook_library().
 *
   drupal_add_library('libraryinfo', 'libraryinfo_angularjs');
 *
 */
function libraryinfo_library() {
  $libraries = array();

   /**
   * load library "Date Range Picker for Bootstrap"
   * load Moment.js library which version is 2.8.4
   *
   * load daterangepicker js and css library
   * load daterangepicker_controller to call js function
   */
  $date_picker_path = drupal_get_path('module', 'libraryinfo') . '/' . 'daterangepicker/';
  $date_picker_lib_path = libraries_get_path('daterangepicker') . '/';
  $libraries['dashpage_date_range_picker'] = array(
    'title' => 'Date Range Picker for Bootstrap',
    'version' => '1.3.17',
    'website' => 'https://github.com/dangrossman/bootstrap-daterangepicker',
    'js' => array(
      $date_picker_lib_path . 'moment.js' => array(),
      $date_picker_lib_path . 'daterangepicker.js' => array(),
      $date_picker_path . 'daterangepicker_controller.js' => array(),
    ),
    'css' => array(
      $date_picker_lib_path . 'daterangepicker-bs3.css' => array(),
      $date_picker_path . 'daterangepicker-controller.css' => array(),
    ),
  );

   /**
   *
   * load sticky
   */
  $date_sticky_path = drupal_get_path('module', 'libraryinfo') . '/' . 'sticky/';
  $date_sticky_lib_path = libraries_get_path('sticky') . '/';
  $libraries['dashpage_sticky'] = array(
    'title' => 'To keep DIV position fixed',
    'version' => '',
    'website' => '',
    'js' => array(
      $date_sticky_lib_path . 'jquery.sticky.js' => array(),
    ),

  );

  /**
   * "Datatables"
   */
  $libraries['libraryinfo_datatables'] = array(
    'title' => 'Datatables',
    'version' => '1.10.10',
    'website' => 'http://datatables.net/',
    'js' => array(
      'https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js' => array('type' => 'external'),
    ),
    'css' => array(
      'https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css' => array('type' => 'external'),
    ),
  );

  /**
   * "AngularJS Material Design"
   */
  $libraries['libraryinfo_angularMaterialjs'] = array(
    'title' => 'AngularMaterial',
    'version' => '1.0.0-rc4',
    'website' => 'https://github.com/angular/material#cdn',
    'js' => array(
      'https://ajax.googleapis.com/ajax/libs/angular_material/0.11.2/angular-material.min.js' => array('type' => 'external'),
    ),
    'css' => array(
      'https://ajax.googleapis.com/ajax/libs/angular_material/0.11.2/angular-material.min.css' => array('type' => 'external'),
    ),
  );

  /**
   * "AngularJS "
   */
  $libraries['libraryinfo_angularjs'] = array(
    'title' => 'AngularJS',
    'version' => '1.4.7',
    'website' => 'https://angularjs.org/',
    'js' => array(
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-route.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-animate.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-aria.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-sanitize.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-messages.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-resource.min.js' => array('type' => 'external'),
      'https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.14.3/ui-bootstrap.js' => array('type' => 'external'),
      'https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.14.3/ui-bootstrap-tpls.min.js' => array('type' => 'external'),
    ),
  );

  /**
   * "Angular Material"
   */
  $libraries['libraryinfo_angularjs_material'] = array(
    'title' => 'Angular Material',
    'version' => 'v0.11.2',
    'website' => 'https://github.com/angular/material#bower',
    'js' => array(
      'https://ajax.googleapis.com/ajax/libs/angular_material/0.11.2/angular-material.min.js' => array('type' => 'external'),
    ),
    'css' => array(
      'https://ajax.googleapis.com/ajax/libs/angular_material/0.11.2/angular-material.min.css' => array('type' => 'external'),
    ),
  );

  /**
   * "Angular UI Sortable "
   */
  $angular_ui_sortable_path = libraries_get_path('angular-ui') . '/';
  $libraries['libraryinfo_angular_ui_sortable'] = array(
    'title' => 'Angular UI Sortable',
    'version' => 'v0.13.4',
    'website' => 'https://github.com/angular-ui/ui-sortable',
    'js' => array(
      $angular_ui_sortable_path . 'ui-sortable-master/src/sortable.js' => array(),
    ),
  );

  /**
   * bootstrap-material-design-master
   */
  $bootstrap_material_design_path = libraries_get_path('bootstrap-material-design-master') . '/';
  $libraries['libraryinfo_bootstrap_material_design'] = array(
    'title' => 'bootstrap material design',
    'version' => 'v',
    'website' => 'http://fezvrasta.github.io/bootstrap-material-design',
    'js' => array(
      $bootstrap_material_design_path . 'dist/js/material.min.js' => array(),
      $bootstrap_material_design_path . 'dist/js/ripples.min.js' => array(),
    ),
    'css' => array(
      $bootstrap_material_design_path . 'dist/css/bootstrap-material-design.css' => array(),
      $bootstrap_material_design_path . 'dist/css/ripples.min.css' => array(),
    ),
  );

  /**
   * "Chart.js" is Simple, clean and engaging charts for designers and developers
   * https://github.com/nnnick/Chart.js
   */
  $libraries['libraryinfo_chart_js'] = array(
    'title' => 'Chart JS',
    'version' => '1.0.2',
    'website' => 'http://chartjs.org/',
    'js' => array(
      'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js' => array('type' => 'external'),
      'https://cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js' => array('type' => 'external'),
      'https://cdnjs.cloudflare.com/ajax/libs/numeral.js/1.4.5/numeral.min.js' => array('type' => 'external'),
    ),
    'css' => array(
      'https://cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.css' => array('type' => 'external'),
    ),
  );

  /**
   * load library "Chosen"
   * Chosen is a jQuery plugin that makes long, unwieldy select boxes much more user-friendly.
   */
  $chosen_path = libraries_get_path('chosen_v1.4.2') . '/';
  $libraries['libraryinfo_chosen'] = array(
    'title' => 'Chosen jQuery select',
    'version' => '1.4.2',
    'website' => 'http://harvesthq.github.io/chosen/',
    'js' => array(
      $chosen_path . 'chosen.jquery.min.js' => array(),
    ),
    'css' => array(
      $chosen_path . 'chosen.min.css' => array(),
    ),
  );

  /**
   * "Font Awesome"
   * Font Awesome is a jQuery plugin that gives you the ability to make any element on your page always stay visible.
   */
  $font_awsome_path = libraries_get_path('font-awesome-4.4.0') . '/';
  $libraries['libraryinfo_font_awsome'] = array(
    'title' => 'Font Awesome',
    'version' => 'v4.4.0 ',
    'website' => 'https://github.com/FortAwesome/Font-Awesome/',
    'css' => array(
      $font_awsome_path . 'css/font-awesome.min.css' => array(),
    ),
  );

  /**
   * html2canvas
   */
  $html2canvas_path = libraries_get_path('html2canvas') . '/';
  $libraries['libraryinfo_html2canvas'] = array(
    'title' => 'html2canvas',
    'version' => '0.5.0-alpha1 ',
    'website' => 'html2canvas.hertzen.com',
    'js' => array(
      $html2canvas_path . 'html2canvas.js' => array(),
    ),
  );

  /**
   * jQuery UI
   */
  $jquery_ui_path = libraries_get_path('jquery-ui-1.11.4') . '/';
  $libraries['libraryinfo_jquery_ui'] = array(
    'title' => 'jQuery UI',
    'version' => '1.11.4 ',
    'website' => 'http://jqueryui.com/',
    'js' => array(
      $jquery_ui_path . 'jquery-ui.min.js' => array(),
    ),
    'css' => array(
      $jquery_ui_path . 'jquery-ui.min.css' => array(),
    ),
  );

  /**
   * load library "Google Map API" v=3.19
   * Load library "infobubble library"
   * load Google Map "markerclusterer" library which version is 2.8.4
   * load Full Screen Google maps liberary
   *
   * load google_maps_meeting_controller to display meeting map
   */
  $google_map_path = drupal_get_path('module', 'libraryinfo') . '/' . 'google_map/';
  $google_map_lib_path = libraries_get_path('google_map') . '/';
  $libraries['dashpage_google_map_api'] = array(
    'title' => 'Google Maps JavaScript API v3',
    'version' => 'v3',
    'website' => 'https://developers.google.com/maps/documentation/javascript/tutorial',
    'js' => array(
      'https://maps-api-ssl.google.com/maps/api/js?v=3.19&key=AIzaSyArFCt613Wu9WzbAK3EmkmbfLwyvJALnQU' => array('type' => 'external'),
      // 'https://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobubble/src/infobubble-compiled.js' => array('type' => 'external'),
      $google_map_lib_path . 'google-map-infobubble-compiled.js' => array(),
      $google_map_lib_path . 'markerclustererplus.js' => array(),
      $google_map_lib_path . 'FullScreenControl.js' => array(),
      $google_map_path . 'google_maps_meeting_controller.js' => array(),
    ),
  );

  /**
   * load library "ngCsv" ng-csv
   *
   * need adding angular-sanitize.min.js
   */
  $ngcsv_path = libraries_get_path('ng-csv-master') . '/';
  $libraries['libraryinfo_ngcsv'] = array(
    'title' => 'ngCsv',
    'version' => '1.0',
    'website' => 'https://github.com/asafdav/ng-csv',
    'js' => array(
      $ngcsv_path . 'build/ng-csv.min.js' => array(),
    ),
  );

  /** - - - - - - return - - - - - - - - - - - - - - - - - - - - - - - - - -  */

  return $libraries;
}

